application: grancalavera-sandbox
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /create_banner
  script: main.py
  login: required

- url: /populate
  script: populate.py
  login: admin

- url: .*
  script: main.py

builtins:
- datastore_admin: on
- remote_api: on